export const ItemType = {
  // Block Items
  GRASS: 'grass',
  DIRT: 'dirt',
  STONE: 'stone',
  WOOD: 'wood',
  LEAF: 'leaf',
  BRICK: 'brick',
  GLASS: 'glass',
  WATER: 'water',
  SAND: 'sand',
  COAL: 'coal',
  IRON: 'iron',
  DIAMOND: 'diamond',
  CHEST: 'chest',
  LEVER: 'lever',
  BIRCH_WOOD: 'birch_wood',
  BIRCH_LEAVES: 'birch_leaves',
  SPRUCE_WOOD: 'spruce_wood',
  SPRUCE_LEAVES: 'spruce_leaves',
  CACTUS: 'cactus',
  JUNGLE_WOOD: 'jungle_wood',
  JUNGLE_LEAVES: 'jungle_leaves',
  SANDSTONE: 'sandstone',
  OAK_SAPLING: 'oak_sapling',
  BIRCH_SAPLING: 'birch_sapling',
  SPRUCE_SAPLING: 'spruce_sapling',
  JUNGLE_SAPLING: 'jungle_sapling',
  DANDELION: 'dandelion',
  POPPY: 'poppy',
  BLUE_ORCHID: 'blue_orchid',
  ALLIUM: 'allium',
  OXEYE_DAISY: 'oxeye_daisy',
  TALL_GRASS: 'tall_grass',
  FERN: 'fern',
  DEAD_BUSH: 'dead_bush',
  SUNFLOWER: 'sunflower',
  ROSE_BUSH: 'rose_bush',
  PEONY: 'peony',
  LILAC: 'lilac',
  DOUBLE_TALL_GRASS: 'double_tall_grass',

  // Pure Items
  PORKCHOP: 'porkchop',
  APPLE: 'apple',
  SEED: 'seed',
} as const;

export type ItemType = typeof ItemType[keyof typeof ItemType];
