import { BlockType, BLOCK_TYPES, SoundType } from '@type';
export { BlockType, BLOCK_TYPES };

export interface BlockProperties {
  id: BlockType;
  name: string;
  isSolid: boolean;           // 是否为实体，供物理碰撞检测使用 (如玩家是否可以穿过)
  isTransparent: boolean;     // 是否为透明/透光方块 (光线穿过、网格绘制时是否剔除邻面)
  isLiquid: boolean;          // 是否为液体 (如水、岩浆等)
  hardness: number;           // 挖掘硬度 (-1表示不可破坏如基岩，0表示即时破坏，1.0为泥土，2.0为石头等)
  affectedByGravity: boolean; // 是否受重力影响 (如沙子、红沙、砾石在没有支撑时会下落)
  lightLevel: number;         // 光照亮度等级：0-15 (如南瓜灯/火把/荧石为15)
  isInteractable: boolean;    // 是否可交互 (如箱子、门、熔炉、拉杆等)
  opacity: number;            // 渲染不透明度：0.0到1.0 (如水 0.8，空气 0.0，玻璃 0.3，普通方块 1.0)
  soundType: SoundType;       // 破坏/放置/行走音效类型
  showBreakCracks?: boolean;  // 破坏过程中是否显示裂纹，默认 true
  color?: string;             // UI preview color (hex string like '#56a032' or rgba)
  colorHex?: number;          // 3D particle/material color (number like 0x56a032)
  border?: string;            // UI preview border (optional)
  allowVegetationBase?: boolean; // 是否允许在此方块上方生成或种植植被/树木/植物 (作为植被生长地基)
  textureFaces?: { top: number; bottom: number; side: number };
}

export const BLOCK_PROPERTIES: Record<number, BlockProperties> = {
  [BLOCK_TYPES.AIR]: {
    id: BLOCK_TYPES.AIR,
    name: '空气',
    isSolid: false,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.0,
    soundType: 'none',
    showBreakCracks: false,
    color: 'transparent',
    colorHex: 0x000000,
  },
  [BLOCK_TYPES.GRASS]: {
    id: BLOCK_TYPES.GRASS,
    name: '草方块',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 0.6,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'grass',
    color: '#56a032',
    colorHex: 0x56a032,
    allowVegetationBase: true,
  },
  [BLOCK_TYPES.DIRT]: {
    id: BLOCK_TYPES.DIRT,
    name: '泥土',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 0.5,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'grass',
    color: '#825a3c',
    colorHex: 0x825a3c,
    allowVegetationBase: true,
  },
  [BLOCK_TYPES.STONE]: {
    id: BLOCK_TYPES.STONE,
    name: '石头',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 1.5,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'stone',
    color: '#787878',
    colorHex: 0x787878,
    allowVegetationBase: true,
  },
  [BLOCK_TYPES.WOOD]: {
    id: BLOCK_TYPES.WOOD,
    name: '原木',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 2.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'wood',
    color: '#78552d',
    colorHex: 0x78552d,
  },
  [BLOCK_TYPES.LEAF]: {
    id: BLOCK_TYPES.LEAF,
    name: '树叶',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#2d7823',
    colorHex: 0x2d7823,
  },
  [BLOCK_TYPES.BRICK]: {
    id: BLOCK_TYPES.BRICK,
    name: '红砖',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 2.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'stone',
    color: '#b85c38',
    colorHex: 0xa03c2d,
  },
  [BLOCK_TYPES.GLASS]: {
    id: BLOCK_TYPES.GLASS,
    name: '玻璃',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0.3,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.3,
    soundType: 'glass',
    showBreakCracks: false,
    color: 'rgba(150, 230, 255, 0.35)',
    colorHex: 0xe0f7fa,
    border: '1.5px solid #96e6ff',
  },
  [BLOCK_TYPES.WATER]: {
    id: BLOCK_TYPES.WATER,
    name: '水',
    isSolid: false,
    isTransparent: true,
    isLiquid: true,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.8,
    soundType: 'water',
    showBreakCracks: false,
    color: 'rgba(40, 110, 220, 0.75)',
    colorHex: 0x286edc,
  },
  [BLOCK_TYPES.SAND]: {
    id: BLOCK_TYPES.SAND,
    name: '沙子',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 0.5,
    affectedByGravity: true,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'sand',
    color: '#dccd8c',
    colorHex: 0xdccd8c,
    allowVegetationBase: true,
  },
  [BLOCK_TYPES.COAL]: {
    id: BLOCK_TYPES.COAL,
    name: '煤矿石',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 3.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'stone',
    color: '#2c2c2c',
    colorHex: 0x282828,
  },
  [BLOCK_TYPES.IRON]: {
    id: BLOCK_TYPES.IRON,
    name: '铁矿石',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 3.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'stone',
    color: '#d0b090',
    colorHex: 0xbe825a,
  },
  [BLOCK_TYPES.DIAMOND]: {
    id: BLOCK_TYPES.DIAMOND,
    name: '钻石矿石',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 3.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'stone',
    color: '#5cdcfa',
    colorHex: 0x5cdcfa,
    border: '1.5px solid #2db4d2',
  },
  [BLOCK_TYPES.BIRCH_WOOD]: {
    id: BLOCK_TYPES.BIRCH_WOOD,
    name: '桦木',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 2.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'wood',
    color: '#dcdcdc',
    colorHex: 0xdcdcdc,
  },
  [BLOCK_TYPES.BIRCH_LEAVES]: {
    id: BLOCK_TYPES.BIRCH_LEAVES,
    name: '桦树叶',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0.2,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#8fc04e',
    colorHex: 0x8fc04e,
  },
  [BLOCK_TYPES.SPRUCE_WOOD]: {
    id: BLOCK_TYPES.SPRUCE_WOOD,
    name: '松木',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 2.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'wood',
    color: '#5c4033',
    colorHex: 0x5c4033,
  },
  [BLOCK_TYPES.SPRUCE_LEAVES]: {
    id: BLOCK_TYPES.SPRUCE_LEAVES,
    name: '松树叶',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0.2,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#2d5a27',
    colorHex: 0x2d5a27,
  },
  [BLOCK_TYPES.CACTUS]: {
    id: BLOCK_TYPES.CACTUS,
    name: '仙人掌',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0.4,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'grass',
    color: '#2d7823',
    colorHex: 0x2d7823,
  },
  [BLOCK_TYPES.JUNGLE_WOOD]: {
    id: BLOCK_TYPES.JUNGLE_WOOD,
    name: '丛林木',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 2.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'wood',
    color: '#5c4033',
    colorHex: 0x5c4033,
  },
  [BLOCK_TYPES.JUNGLE_LEAVES]: {
    id: BLOCK_TYPES.JUNGLE_LEAVES,
    name: '丛林叶',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0.2,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#1a5f12',
    colorHex: 0x1a5f12,
  },
  [BLOCK_TYPES.SANDSTONE]: {
    id: BLOCK_TYPES.SANDSTONE,
    name: '砂岩',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 0.8,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'stone',
    color: '#d2b48c',
    colorHex: 0xd2b48c,
  },
};

// Let propertiesResolver fall back to local static BLOCK_PROPERTIES initially,
// then override it from BlockRegistry at runtime.
let propertiesResolver: (blockId: number) => BlockProperties = (blockId) => {
  return BLOCK_PROPERTIES[blockId] || BLOCK_PROPERTIES[BLOCK_TYPES.AIR];
};

export function setPropertiesResolver(resolver: (blockId: number) => BlockProperties) {
  propertiesResolver = resolver;
}

// Helper function to safely fetch properties of any block ID, defaulting to AIR properties
export function getBlockProperties(blockId: number): BlockProperties {
  return propertiesResolver(blockId & 0x3F);
}


