import { BlockType, BLOCK_TYPES, SoundType } from '@type';
export { BlockType, BLOCK_TYPES };

export interface BlockProperties {
  id: BlockType;
  name: string;
  isSolid: boolean;           // 是否为实体，供物理碰撞检测使用 (如玩家是否可以穿过)
  isTransparent: boolean;     // 是否为透明/透光方块 (光线穿过、网格绘制时是否剔除邻面)
  isLiquid: boolean;          // 是否为液体 (如水、岩浆等)
  hardness: number;           // 挖掘硬度 (-1表示不可破坏如基岩，0表示即时破坏，1.0为泥土，2.0为石头等)
  affectedByGravity: boolean; // 是否受重力影响 (如沙子、红沙、砾石在没有支撑时会下落)
  lightLevel: number;         // 光照亮度等级：0-15 (如南瓜灯/火把/荧石为15)
  isInteractable: boolean;    // 是否可交互 (如箱子、门、熔炉、拉杆等)
  opacity: number;            // 渲染不透明度：0.0到1.0 (如水 0.8，空气 0.0，玻璃 0.3，普通方块 1.0)
  soundType: SoundType;       // 破坏/放置/行走音效类型
  showBreakCracks?: boolean;  // 破坏过程中是否显示裂纹，默认 true
  color?: string;             // UI preview color (hex string like '#56a032' or rgba)
  colorHex?: number;          // 3D particle/material color (number like 0x56a032)
  border?: string;            // UI preview border (optional)
  allowVegetationBase?: boolean; // 是否允许在此方块上方生成或种植植被/树木/植物 (作为植被生长地基)
  textureFaces?: { top: number; bottom: number; side: number };
  droppedModelType?: 'block' | 'cross';
  renderAdjacentSameType?: boolean; // 当相邻方块是相同类型时是否依然渲染邻面 (例如树叶)
  renderInternalCross?: boolean;     // 是否在方块内部渲染交叉的斜对角平面 (例如树叶的高级效果)
  isCrossModel?: boolean;            // 是否作为交叉的斜对角平面模型渲染 (而非普通的立方体方块)
  crossScaleW?: number;              // 交叉模型宽度缩放比例 (如 0.6)
  crossScaleH?: number;              // 交叉模型高度缩放比例 (如 0.7)
  enableCrossOffset?: boolean;       // 是否启用斜对角平面随机微调偏移 (避免完美网格对齐)
  isCollidable?: boolean;     // 是否参与物理碰撞，未指定时默认为 isSolid
  canSpawnOn?: boolean;       // 是否允许在其上方出生，未指定时默认为 isSolid && !isTransparent && !isLiquid
}

export const BLOCK_PROPERTIES: Record<number, BlockProperties> = {
  [BLOCK_TYPES.AIR]: {
    id: BLOCK_TYPES.AIR,
    name: '空气',
    isSolid: false,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.0,
    soundType: 'none',
    showBreakCracks: false,
    color: 'transparent',
    colorHex: 0x000000,
  },
  [BLOCK_TYPES.GRASS]: {
    id: BLOCK_TYPES.GRASS,
    name: '草方块',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 0.6,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'grass',
    color: '#56a032',
    colorHex: 0x56a032,
    allowVegetationBase: true,
  },
  [BLOCK_TYPES.DIRT]: {
    id: BLOCK_TYPES.DIRT,
    name: '泥土',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 0.5,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'grass',
    color: '#825a3c',
    colorHex: 0x825a3c,
    allowVegetationBase: true,
  },
  [BLOCK_TYPES.STONE]: {
    id: BLOCK_TYPES.STONE,
    name: '石头',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 1.5,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'stone',
    color: '#787878',
    colorHex: 0x787878,
    allowVegetationBase: true,
  },
  [BLOCK_TYPES.WOOD]: {
    id: BLOCK_TYPES.WOOD,
    name: '原木',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 2.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'wood',
    color: '#78552d',
    colorHex: 0x78552d,
  },
  [BLOCK_TYPES.LEAF]: {
    id: BLOCK_TYPES.LEAF,
    name: '树叶',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#2d7823',
    colorHex: 0x2d7823,
  },
  [BLOCK_TYPES.BRICK]: {
    id: BLOCK_TYPES.BRICK,
    name: '红砖',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 2.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'stone',
    color: '#b85c38',
    colorHex: 0xa03c2d,
  },
  [BLOCK_TYPES.GLASS]: {
    id: BLOCK_TYPES.GLASS,
    name: '玻璃',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0.3,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.3,
    soundType: 'glass',
    showBreakCracks: false,
    color: 'rgba(150, 230, 255, 0.35)',
    colorHex: 0xe0f7fa,
    border: '1.5px solid #96e6ff',
  },
  [BLOCK_TYPES.WATER]: {
    id: BLOCK_TYPES.WATER,
    name: '水',
    isSolid: false,
    isTransparent: true,
    isLiquid: true,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.8,
    soundType: 'water',
    showBreakCracks: false,
    color: 'rgba(40, 110, 220, 0.75)',
    colorHex: 0x286edc,
  },
  [BLOCK_TYPES.SAND]: {
    id: BLOCK_TYPES.SAND,
    name: '沙子',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 0.5,
    affectedByGravity: true,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'sand',
    color: '#dccd8c',
    colorHex: 0xdccd8c,
    allowVegetationBase: true,
  },
  [BLOCK_TYPES.COAL]: {
    id: BLOCK_TYPES.COAL,
    name: '煤矿石',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 3.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'stone',
    color: '#2c2c2c',
    colorHex: 0x282828,
  },
  [BLOCK_TYPES.IRON]: {
    id: BLOCK_TYPES.IRON,
    name: '铁矿石',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 3.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'stone',
    color: '#d0b090',
    colorHex: 0xbe825a,
  },
  [BLOCK_TYPES.DIAMOND]: {
    id: BLOCK_TYPES.DIAMOND,
    name: '钻石矿石',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 3.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'stone',
    color: '#5cdcfa',
    colorHex: 0x5cdcfa,
    border: '1.5px solid #2db4d2',
  },
  [BLOCK_TYPES.BIRCH_WOOD]: {
    id: BLOCK_TYPES.BIRCH_WOOD,
    name: '桦木',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 2.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'wood',
    color: '#dcdcdc',
    colorHex: 0xdcdcdc,
  },
  [BLOCK_TYPES.BIRCH_LEAVES]: {
    id: BLOCK_TYPES.BIRCH_LEAVES,
    name: '桦树叶',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0.2,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#8fc04e',
    colorHex: 0x8fc04e,
  },
  [BLOCK_TYPES.SPRUCE_WOOD]: {
    id: BLOCK_TYPES.SPRUCE_WOOD,
    name: '松木',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 2.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'wood',
    color: '#5c4033',
    colorHex: 0x5c4033,
  },
  [BLOCK_TYPES.SPRUCE_LEAVES]: {
    id: BLOCK_TYPES.SPRUCE_LEAVES,
    name: '松树叶',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0.2,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#2d5a27',
    colorHex: 0x2d5a27,
  },
  [BLOCK_TYPES.CACTUS]: {
    id: BLOCK_TYPES.CACTUS,
    name: '仙人掌',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0.4,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'grass',
    color: '#2d7823',
    colorHex: 0x2d7823,
  },
  [BLOCK_TYPES.JUNGLE_WOOD]: {
    id: BLOCK_TYPES.JUNGLE_WOOD,
    name: '丛林木',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 2.0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'wood',
    color: '#5c4033',
    colorHex: 0x5c4033,
  },
  [BLOCK_TYPES.JUNGLE_LEAVES]: {
    id: BLOCK_TYPES.JUNGLE_LEAVES,
    name: '丛林叶',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0.2,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#1a5f12',
    colorHex: 0x1a5f12,
  },
  [BLOCK_TYPES.SANDSTONE]: {
    id: BLOCK_TYPES.SANDSTONE,
    name: '砂岩',
    isSolid: true,
    isTransparent: false,
    isLiquid: false,
    hardness: 0.8,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 1.0,
    soundType: 'stone',
    color: '#d2b48c',
    colorHex: 0xd2b48c,
  },
  [BLOCK_TYPES.OAK_SAPLING]: {
    id: BLOCK_TYPES.OAK_SAPLING,
    name: '橡树树苗',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#4c9436',
    colorHex: 0x4c9436,
    textureFaces: { top: 28, bottom: 28, side: 28 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.6,
    crossScaleH: 0.7,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.BIRCH_SAPLING]: {
    id: BLOCK_TYPES.BIRCH_SAPLING,
    name: '桦树树苗',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#8fc04e',
    colorHex: 0x8fc04e,
    textureFaces: { top: 29, bottom: 29, side: 29 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.6,
    crossScaleH: 0.7,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.SPRUCE_SAPLING]: {
    id: BLOCK_TYPES.SPRUCE_SAPLING,
    name: '松树树苗',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#2d5a27',
    colorHex: 0x2d5a27,
    textureFaces: { top: 30, bottom: 30, side: 30 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.6,
    crossScaleH: 0.7,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.JUNGLE_SAPLING]: {
    id: BLOCK_TYPES.JUNGLE_SAPLING,
    name: '丛林树苗',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#1a5f12',
    colorHex: 0x1a5f12,
    textureFaces: { top: 31, bottom: 31, side: 31 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.6,
    crossScaleH: 0.7,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.DANDELION]: {
    id: BLOCK_TYPES.DANDELION,
    name: '蒲公英',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#ffeb3b',
    colorHex: 0xffeb3b,
    textureFaces: { top: 34, bottom: 34, side: 34 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.6,
    crossScaleH: 0.65,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.POPPY]: {
    id: BLOCK_TYPES.POPPY,
    name: '玫瑰',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#f44336',
    colorHex: 0xf44336,
    textureFaces: { top: 35, bottom: 35, side: 35 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.6,
    crossScaleH: 0.65,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.BLUE_ORCHID]: {
    id: BLOCK_TYPES.BLUE_ORCHID,
    name: '兰花',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#2196f3',
    colorHex: 0x2196f3,
    textureFaces: { top: 36, bottom: 36, side: 36 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.6,
    crossScaleH: 0.65,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.ALLIUM]: {
    id: BLOCK_TYPES.ALLIUM,
    name: '绒球葱',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#e040fb',
    colorHex: 0xe040fb,
    textureFaces: { top: 37, bottom: 37, side: 37 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.6,
    crossScaleH: 0.65,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.OXEYE_DAISY]: {
    id: BLOCK_TYPES.OXEYE_DAISY,
    name: '雏菊',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#eeeeee',
    colorHex: 0xeeeeee,
    textureFaces: { top: 38, bottom: 38, side: 38 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.6,
    crossScaleH: 0.65,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.TALL_GRASS]: {
    id: BLOCK_TYPES.TALL_GRASS,
    name: '草丛',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#4caf50',
    colorHex: 0x4caf50,
    textureFaces: { top: 39, bottom: 39, side: 39 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.85,
    crossScaleH: 0.85,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.FERN]: {
    id: BLOCK_TYPES.FERN,
    name: '蕨',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#388e3c',
    colorHex: 0x388e3c,
    textureFaces: { top: 40, bottom: 40, side: 40 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.85,
    crossScaleH: 0.85,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.DEAD_BUSH]: {
    id: BLOCK_TYPES.DEAD_BUSH,
    name: '枯萎的灌木',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#a08060',
    colorHex: 0xa08060,
    textureFaces: { top: 41, bottom: 41, side: 41 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.75,
    crossScaleH: 0.75,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.SUNFLOWER_BOTTOM]: {
    id: BLOCK_TYPES.SUNFLOWER_BOTTOM,
    name: '向日葵(底)',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#4caf50',
    colorHex: 0x4caf50,
    textureFaces: { top: 42, bottom: 42, side: 42 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.85,
    crossScaleH: 1.0,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.SUNFLOWER_TOP]: {
    id: BLOCK_TYPES.SUNFLOWER_TOP,
    name: '向日葵(顶)',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#ffeb3b',
    colorHex: 0xffeb3b,
    textureFaces: { top: 43, bottom: 43, side: 43 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.85,
    crossScaleH: 1.0,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.ROSE_BUSH_BOTTOM]: {
    id: BLOCK_TYPES.ROSE_BUSH_BOTTOM,
    name: '玫瑰丛(底)',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#4caf50',
    colorHex: 0x4caf50,
    textureFaces: { top: 44, bottom: 44, side: 44 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.85,
    crossScaleH: 1.0,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.ROSE_BUSH_TOP]: {
    id: BLOCK_TYPES.ROSE_BUSH_TOP,
    name: '玫瑰丛(顶)',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#f44336',
    colorHex: 0xf44336,
    textureFaces: { top: 45, bottom: 45, side: 45 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.85,
    crossScaleH: 1.0,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.PEONY_BOTTOM]: {
    id: BLOCK_TYPES.PEONY_BOTTOM,
    name: '牡丹(底)',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#4caf50',
    colorHex: 0x4caf50,
    textureFaces: { top: 46, bottom: 46, side: 46 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.85,
    crossScaleH: 1.0,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.PEONY_TOP]: {
    id: BLOCK_TYPES.PEONY_TOP,
    name: '牡丹(顶)',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#f8bbd0',
    colorHex: 0xf8bbd0,
    textureFaces: { top: 47, bottom: 47, side: 47 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.85,
    crossScaleH: 1.0,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.LILAC_BOTTOM]: {
    id: BLOCK_TYPES.LILAC_BOTTOM,
    name: '丁香(底)',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#4caf50',
    colorHex: 0x4caf50,
    textureFaces: { top: 48, bottom: 48, side: 48 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.85,
    crossScaleH: 1.0,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.LILAC_TOP]: {
    id: BLOCK_TYPES.LILAC_TOP,
    name: '丁香(顶)',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#d1c4e9',
    colorHex: 0xd1c4e9,
    textureFaces: { top: 49, bottom: 49, side: 49 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.85,
    crossScaleH: 1.0,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.DOUBLE_TALL_GRASS_BOTTOM]: {
    id: BLOCK_TYPES.DOUBLE_TALL_GRASS_BOTTOM,
    name: '双格高草(底)',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#4caf50',
    colorHex: 0x4caf50,
    textureFaces: { top: 50, bottom: 50, side: 50 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.85,
    crossScaleH: 1.0,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
  [BLOCK_TYPES.DOUBLE_TALL_GRASS_TOP]: {
    id: BLOCK_TYPES.DOUBLE_TALL_GRASS_TOP,
    name: '双格高草(顶)',
    isSolid: true,
    isTransparent: true,
    isLiquid: false,
    hardness: 0,
    affectedByGravity: false,
    lightLevel: 0,
    isInteractable: false,
    opacity: 0.5,
    soundType: 'grass',
    color: '#81c784',
    colorHex: 0x81c784,
    textureFaces: { top: 51, bottom: 51, side: 51 },
    droppedModelType: 'cross',
    isCollidable: false,
    isCrossModel: true,
    crossScaleW: 0.85,
    crossScaleH: 1.0,
    enableCrossOffset: true,
    canSpawnOn: false,
  },
};


// Let propertiesResolver fall back to local static BLOCK_PROPERTIES initially,
// then override it from BlockRegistry at runtime.
let propertiesResolver: (blockId: number) => BlockProperties = (blockId) => {
  return BLOCK_PROPERTIES[blockId] || BLOCK_PROPERTIES[BLOCK_TYPES.AIR];
};

export function setPropertiesResolver(resolver: (blockId: number) => BlockProperties) {
  propertiesResolver = resolver;
}

// Helper function to safely fetch properties of any block ID, defaulting to AIR properties
export function getBlockProperties(blockId: number): BlockProperties {
  const props = propertiesResolver(blockId & 0x3F);
  return {
    ...props,
    isCollidable: props.isCollidable ?? props.isSolid,
    canSpawnOn: props.canSpawnOn ?? (props.isSolid && !props.isTransparent && !props.isLiquid)
  };
}


